-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2012/5/11 17:43:00
-- Server version: 5.5.17
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE eHR;

--
-- Definition for table bonus
--
DROP TABLE IF EXISTS bonus;
CREATE TABLE bonus (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '奖金名称(无,每月提成,季度提成等)',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '奖金';

--
-- Definition for table businessArea
--
DROP TABLE IF EXISTS businessArea;
CREATE TABLE businessArea (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '商区名称',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '商区';

--
-- Definition for table ci_sessions
--
DROP TABLE IF EXISTS ci_sessions;
CREATE TABLE ci_sessions (
  session_id VARCHAR(40) NOT NULL DEFAULT '0',
  ip_address VARCHAR(16) NOT NULL DEFAULT '0',
  user_agent VARCHAR(50) NOT NULL,
  last_activity INT(10) UNSIGNED NOT NULL DEFAULT 0,
  user_data TEXT NOT NULL,
  PRIMARY KEY (session_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 176
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table city
--
DROP TABLE IF EXISTS city;
CREATE TABLE city (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '城市名称',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '城市';

--
-- Definition for table commissionDate
--
DROP TABLE IF EXISTS commissionDate;
CREATE TABLE commissionDate (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '佣金支付期限(即时，1个月，3个月)',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '佣金支付期限';

--
-- Definition for table commonLevel
--
DROP TABLE IF EXISTS commonLevel;
CREATE TABLE commonLevel (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '级别名称(一般,良好,优秀等)',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '通用级别';

--
-- Definition for table contractType
--
DROP TABLE IF EXISTS contractType;
CREATE TABLE contractType (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '合同类型名称(全职,兼职,小时工等)',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '合同类型';

--
-- Definition for table deal
--
DROP TABLE IF EXISTS deal;
CREATE TABLE deal (
  id INT(11) NOT NULL AUTO_INCREMENT,
  talent INT(11) NOT NULL COMMENT '人才',
  job INT(11) NOT NULL COMMENT '职位',
  enterpriseNote TEXT DEFAULT NULL COMMENT '企业备注',
  accurate INT(11) NOT NULL COMMENT '准确程度',
  communication INT(11) NOT NULL COMMENT '顺畅程度',
  quality INT(11) NOT NULL COMMENT '质量',
  enterpriseRemark TEXT NOT NULL COMMENT '企业评价',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '交易';

--
-- Definition for table dealHistory
--
DROP TABLE IF EXISTS dealHistory;
CREATE TABLE dealHistory (
  id INT(11) NOT NULL AUTO_INCREMENT,
  deal INT(11) NOT NULL COMMENT '交易',
  status INT(11) NOT NULL COMMENT '交易状态',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '交易状态历史';

--
-- Definition for table dealStatus
--
DROP TABLE IF EXISTS dealStatus;
CREATE TABLE dealStatus (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '交易状态名称',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '交易状态';

--
-- Definition for table education
--
DROP TABLE IF EXISTS education;
CREATE TABLE education (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '学历名称',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '学历';

--
-- Definition for table enterprise
--
DROP TABLE IF EXISTS enterprise;
CREATE TABLE enterprise (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '用户名',
  phone VARCHAR(255) DEFAULT NULL COMMENT '电话',
  mail VARCHAR(255) DEFAULT NULL COMMENT '邮件',
  address VARCHAR(255) DEFAULT NULL COMMENT '地址',
  introduction TEXT NOT NULL COMMENT '公司介绍',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '企业';

--
-- Definition for table enterpriseUser
--
DROP TABLE IF EXISTS enterpriseUser;
CREATE TABLE enterpriseUser (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '用户名',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  enterprise INT(11) NOT NULL COMMENT '所属企业id',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '企业用户';

--
-- Definition for table hunter
--
DROP TABLE IF EXISTS hunter;
CREATE TABLE hunter (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '用户名',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  fixphone1 VARCHAR(255) DEFAULT NULL COMMENT '固话区号',
  fixphone2 VARCHAR(255) DEFAULT NULL COMMENT '固话号码',
  fixphone3 VARCHAR(255) DEFAULT NULL COMMENT '固话分机',
  mobile VARCHAR(255) DEFAULT NULL COMMENT '手机',
  personName VARCHAR(255) DEFAULT NULL COMMENT '姓名',
  idNo VARCHAR(255) DEFAULT NULL COMMENT '身份证号码',
  address VARCHAR(255) DEFAULT NULL COMMENT '地址',
  bankNo VARCHAR(255) DEFAULT NULL COMMENT '银行帐号',
  bankName VARCHAR(255) DEFAULT NULL COMMENT '开户行名称',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '猎头';

--
-- Definition for table industry
--
DROP TABLE IF EXISTS industry;
CREATE TABLE industry (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '行业名称',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '行业';

--
-- Definition for table job
--
DROP TABLE IF EXISTS job;
CREATE TABLE job (
  id INT(11) NOT NULL AUTO_INCREMENT,
  creator INT(11) NOT NULL COMMENT '创建者',
  title VARCHAR(255) NOT NULL COMMENT '名称',
  requireNumber INT(11) NOT NULL COMMENT '需要人数',
  jobType INT(11) NOT NULL COMMENT '工作类型(全职,兼职等)',
  contractType INT(11) NOT NULL COMMENT '合同类型(正式员工,合同员工等)',
  workTime INT(11) NOT NULL COMMENT '工作时间(做一休一,做四休三等)',
  city INT(11) NOT NULL COMMENT '城市',
  business INT(11) DEFAULT NULL COMMENT '商区',
  onBoardDate DATE DEFAULT NULL COMMENT '上岗日期',
  salaryFrom INT(11) NOT NULL COMMENT '工资下限',
  salaryTo INT(11) DEFAULT NULL COMMENT '工资上限',
  commissionDate INT(11) NOT NULL COMMENT '佣金支付期限',
  sex INT(11) DEFAULT NULL COMMENT '性别要求',
  ageFrom INT(11) DEFAULT NULL COMMENT '年龄下限',
  ageTo INT(11) DEFAULT NULL COMMENT '年龄上限',
  heightFrom INT(11) DEFAULT NULL COMMENT '身高下限',
  heightTo INT(11) DEFAULT NULL COMMENT '身高上限',
  education INT(11) DEFAULT NULL COMMENT '学历要求',
  specialSkill TEXT DEFAULT NULL COMMENT '特殊技能要求',
  detail TEXT NOT NULL COMMENT '岗位描述',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '职位';

--
-- Definition for table jobBonus
--
DROP TABLE IF EXISTS jobBonus;
CREATE TABLE jobBonus (
  id INT(11) NOT NULL AUTO_INCREMENT,
  job INT(11) NOT NULL COMMENT '职位',
  bonus INT(11) NOT NULL COMMENT '奖金类型',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '职位奖金';

--
-- Definition for table jobLanguage
--
DROP TABLE IF EXISTS jobLanguage;
CREATE TABLE jobLanguage (
  id INT(11) NOT NULL AUTO_INCREMENT,
  job INT(11) NOT NULL COMMENT '职位',
  language INT(11) NOT NULL COMMENT '语言',
  commonLevel INT(11) NOT NULL COMMENT '水平',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '职位语言要求';

--
-- Definition for table jobType
--
DROP TABLE IF EXISTS jobType;
CREATE TABLE jobType (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '工作类型名称(全职,兼职,小时工等)',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '工作类型';

--
-- Definition for table jobWelfare
--
DROP TABLE IF EXISTS jobWelfare;
CREATE TABLE jobWelfare (
  id INT(11) NOT NULL AUTO_INCREMENT,
  job INT(11) NOT NULL COMMENT '职位',
  welfare INT(11) NOT NULL COMMENT '福利类型',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '职位福利';

--
-- Definition for table sex
--
DROP TABLE IF EXISTS sex;
CREATE TABLE sex (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '性别',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '性别';

--
-- Definition for table talent
--
DROP TABLE IF EXISTS talent;
CREATE TABLE talent (
  id INT(11) NOT NULL AUTO_INCREMENT,
  hunter INT(11) NOT NULL COMMENT '所属猎头',
  personName VARCHAR(255) NOT NULL COMMENT '人才姓名',
  photoURL TEXT NOT NULL COMMENT '照片路径',
  videoURL TEXT NOT NULL COMMENT '视频路径',
  sex INT(11) NOT NULL COMMENT '性别',
  marriage TINYINT(1) DEFAULT NULL COMMENT '婚姻',
  height INT(11) DEFAULT NULL COMMENT '身高',
  education INT(11) DEFAULT NULL COMMENT '学历',
  appearance INT(11) DEFAULT NULL COMMENT '外貌',
  expression INT(11) DEFAULT NULL COMMENT '表达能力',
  hunterNote TEXT DEFAULT NULL COMMENT '猎头备注',
  `release` TINYINT(1) NOT NULL COMMENT '是否可以发布',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '人才';

--
-- Definition for table talentFitBusinessArea
--
DROP TABLE IF EXISTS talentFitBusinessArea;
CREATE TABLE talentFitBusinessArea (
  id INT(11) NOT NULL AUTO_INCREMENT,
  talent INT(11) NOT NULL COMMENT '人才',
  businessArea INT(11) NOT NULL COMMENT '商区',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '人才适合商区';

--
-- Definition for table talentFitCity
--
DROP TABLE IF EXISTS talentFitCity;
CREATE TABLE talentFitCity (
  id INT(11) NOT NULL AUTO_INCREMENT,
  talent INT(11) NOT NULL COMMENT '人才',
  city INT(11) NOT NULL COMMENT '城市',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '人才适合城市';

--
-- Definition for table talentFitIndustry
--
DROP TABLE IF EXISTS talentFitIndustry;
CREATE TABLE talentFitIndustry (
  id INT(11) NOT NULL AUTO_INCREMENT,
  talent INT(11) NOT NULL COMMENT '人才',
  industry INT(11) NOT NULL COMMENT '行业',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '人才适合行业';

--
-- Definition for table talentUnfitIndustry
--
DROP TABLE IF EXISTS talentUnfitIndustry;
CREATE TABLE talentUnfitIndustry (
  id INT(11) NOT NULL AUTO_INCREMENT,
  talent INT(11) NOT NULL COMMENT '人才',
  industry INT(11) NOT NULL COMMENT '行业',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '人才不适合行业';

--
-- Definition for table welfare
--
DROP TABLE IF EXISTS welfare;
CREATE TABLE welfare (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '福利名称(无,饭贴,车贴等)',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '其他福利';

--
-- Definition for table workTime
--
DROP TABLE IF EXISTS workTime;
CREATE TABLE workTime (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '工作时间类型名称(做一休一,做四休三等)',
  active TINYINT(1) NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '工作时间类型';

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;